import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Sg({ random, yarn }: { random: number; yarn: string }) {
  return (
    <>
      <Head>
        <title>SG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.title}>
          <p>
            SG PAGE
            <br />
            <h1 className={styles.title}>{random}</h1>
            <h1 className={styles.title}>yarn version: {yarn}</h1>
          </p>
        </div>
        <ul className={styles.description}>
          <li className={styles.title}>
            <Link href="/">HOME(static)</Link>
          </li>
          <li className={styles.title}>
            <Link href="/sg">SG PAGE</Link>
          </li>
          <li className={styles.title}>
            <Link href="/ssr">SSR PAGE</Link>
          </li>
        </ul>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const random = Math.floor(Math.random() * 100);
  const yarn = process.env.YARN;

  console.log('\n++++++++++++++++++++++++++++++++++++');
  console.log('YARN', yarn);
  console.log('SG: ', random);
  console.log('++++++++++++++++++++++++++++++++++++\n');

  return {
    props: {
      random,
      yarn,
    },
  };
}
