import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Sg({ random }: { random: number }) {
  return (
    <>
      <Head>
        <title>SG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="main">
          <p>
            SG PAGE
            <br />
            <em>{random}</em>
          </p>
        </div>
        <ul className={styles.description}>
          <li className={styles.title}>
            <Link href="/">HOME</Link>
          </li>
          <li className={styles.title}>
            <Link href="/sg">SG PAGE</Link>
          </li>
        </ul>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const random = Math.floor(Math.random() * 100);

  console.log('\n++++++++++++++++++++++++++++++++++++');
  console.log('SG: ', random);
  console.log('++++++++++++++++++++++++++++++++++++\n');

  return {
    props: {
      random,
    },
  };
}
